// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/**
 * This code represents a single action taken by a player during the game.
 * A Player can perform an action that involves an intersection, an edge, or both depending on the action type.
 *
 * @author Maria Shashati
 * @version 1.0
 */
public class Action {

    private ActionType type;
    private int intersectionId;
    private int edgeIntersectionA;
    private int edgeIntersectionB;

    /**
     * Constructs an Action with the given parameters.
     *
     * @param type the type of action
     * @param intersectionId the intersection involved in the action
     * @param edgeIntersectionA the first edge intersection
     * @param edgeIntersectionB the second edge intersection
     */
    private Action(ActionType type, int intersectionId, int edgeIntersectionA, int edgeIntersectionB) {
        this.type = type;
        this.intersectionId = intersectionId;
        this.edgeIntersectionA = edgeIntersectionA;
        this.edgeIntersectionB = edgeIntersectionB;
    }

    // Static factory methods
    public static Action buildRoad(int intersectionA, int intersectionB) {
        return new Action(ActionType.BUILD_ROAD, -1, intersectionA, intersectionB);
    }

    public static Action buildSettlement(int intersectionId) {
        return new Action(ActionType.BUILD_SETTLEMENT, intersectionId, -1, -1);
    }

    public static Action buildCity(int intersectionId) {
        return new Action(ActionType.BUILD_CITY, intersectionId, -1, -1);
    }

    public static Action pass() {
        return new Action(ActionType.PASS, -1, -1, -1);
    }

    public ActionType getType() {
        return type;
    }

    public int getIntersectionId() {
        return intersectionId;
    }

    public int getEdgeIntersectionA() {
        return edgeIntersectionA;
    }

    public int getEdgeIntersectionB() {
        return edgeIntersectionB;
    }

  
    /**
     * Returns a human-readable description of the action for logging purposes.
     *
     * @return a string describing the action
     */
    public String describeForLogin() {
    	switch (type) {
        case BUILD_ROAD:
            return "Built road between " + edgeIntersectionA + " and " + edgeIntersectionB;
        case BUILD_SETTLEMENT:
            return "Built settlement at intersection " + intersectionId;
        case BUILD_CITY:
            return "Upgraded to city at intersection " + intersectionId;
        case PASS:
            return "Passed";
        default:
            return "Unknown action";
    }
    
}
}
   



