// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/**
 * The ActionType enum represents the different actions a player can make during their turn.
 *
 * @author Maria Shashati
 *
 */
public enum ActionType {
	
	BUILD_ROAD,
	
	BUILD_SETTLEMENT,
	
	BUILD_CITY,
	
	PASS;
}
