// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Represents the game board for Catan.
 * Stores tiles, intersections, and edges.
 *
 * Tile ID:  center=0, inner ring=1-6, outer ring=7-18
 * Node ID:  0-53
 *
 * @author Rameen Tariq
 * @author Komal Khan (Assignment 2 additions)
 */
public class Board {

    private Tile[] tiles;

    private Intersection[] intersections;
    private Edge[] edges;
    
    /**
     * Maps each intersection ID to the list of adjacent intersection IDs.
     * Built once during initialization and used for distance rule checks.
     */
    private Map<Integer, List<Integer>> adjacentIntersectionIdsByIntersectionId;
    

    /**
     * Maps each intersection ID to the list of adjacent tile IDs.
     * Built once during initialization and used for resource distribution.
     */
    private Map<Integer, List<Integer>> adjacentTileIdsByIntersectionId;

    private int robberTileId;

    /**
     * Creates a new Board and initializes the fixed layout.
     */
    public Board() {
        initializeFixedMapLayout();
    }

    /**
     * Initializes the board with all tiles, intersections, and edges.
     */
    public void initializeFixedMapLayout() {
        tiles = new Tile[19];

        Resources[] resources = {
            Resources.WOOD,
            Resources.WHEAT,
            Resources.BRICK,
            Resources.ORE,
            Resources.SHEEP,
            Resources.SHEEP,
            Resources.SHEEP,
            Resources.WHEAT,
            Resources.ORE,
            Resources.WOOD,
            Resources.ORE,
            Resources.WHEAT,
            Resources.WOOD,
            Resources.BRICK,
            Resources.BRICK,
            Resources.WHEAT,
            Resources.DESERT,
            Resources.WOOD,
            Resources.SHEEP
        };

        int[] diceNumbers = {10, 11, 8, 3, 11, 5, 12, 3, 6, 4, 6, 9, 5, 9, 8, 4, 0, 2, 10};

        for (int i = 0; i < 19; i++) {
            tiles[i] = new Tile(i, resources[i], diceNumbers[i]);
        }

        intersections = new Intersection[54];
        for (int i = 0; i < 54; i++) {
            intersections[i] = new Intersection(i);
        }

        Map<Integer, int[]> tileCorners = new HashMap<>();
        tileCorners.put(0,  new int[]{4, 5, 0, 1, 2, 3});
        tileCorners.put(1,  new int[]{3, 2, 6, 7, 8, 9});
        tileCorners.put(2,  new int[]{9, 8, 10, 11, 12, 13});
        tileCorners.put(3,  new int[]{14, 4, 3, 13, 12, 15});
        tileCorners.put(4,  new int[]{16, 17, 5, 4, 14, 18});
        tileCorners.put(5,  new int[]{19, 20, 21, 17, 16, 22});
        tileCorners.put(6,  new int[]{1, 0, 23, 20, 19, 2});
        tileCorners.put(7,  new int[]{7, 6, 24, 25, 26, 8});
        tileCorners.put(8,  new int[]{11, 10, 27, 28, 29, 12});
        tileCorners.put(9,  new int[]{15, 12, 29, 30, 31, 32});
        tileCorners.put(10, new int[]{18, 14, 15, 32, 33, 34});
        tileCorners.put(11, new int[]{35, 16, 18, 34, 36, 37});
        tileCorners.put(12, new int[]{22, 16, 35, 37, 38, 39});
        tileCorners.put(13, new int[]{19, 22, 39, 40, 41, 20});
        tileCorners.put(14, new int[]{23, 0, 1, 41, 42, 43});
        tileCorners.put(15, new int[]{26, 25, 44, 45, 46, 27});
        tileCorners.put(16, new int[]{29, 28, 46, 47, 48, 30});
        tileCorners.put(17, new int[]{32, 31, 48, 49, 50, 33});
        tileCorners.put(18, new int[]{34, 33, 50, 51, 52, 36});

     // For each intersection, record which tiles it belongs to
        adjacentTileIdsByIntersectionId = new HashMap<>();
        for (int tileId = 0; tileId < 19; tileId++) {
            int[] corners = tileCorners.get(tileId);
            for (int nodeId : corners) {
                adjacentTileIdsByIntersectionId
                    .computeIfAbsent(nodeId, k -> new ArrayList<>())
                    .add(tileId);
            }
        }

        
     // ── Edges and intersection adjacency ──────────────────────────────
        // Walk every tile's corners and add edges between adjacent corners
        // Skip duplicate edges (shared between two tiles)
        adjacentIntersectionIdsByIntersectionId = new HashMap<>();
        List<int[]> edgePairs = new ArrayList<>();

        for (int tileId = 0; tileId < 19; tileId++) {
            int[] c = tileCorners.get(tileId);
            for (int i = 0; i < c.length; i++) {
                int a = c[i];
                int b = c[(i + 1) % c.length];// wrap around to close the hexagon
                
                String key = Math.min(a, b) + "-" + Math.max(a, b);
             // Check if this edge already exists from a previous tile
                boolean found = false;
                for (int[] ep : edgePairs) {
                    if ((ep[0] == a && ep[1] == b) || (ep[0] == b && ep[1] == a)) {
                        found = true;
                        break;
                    }
                }
             // Only add new edges — shared edges between tiles appear twice in corners
                if (!found) {
                    edgePairs.add(new int[]{a, b});
                 // Register both directions in the adjacency map
                    adjacentIntersectionIdsByIntersectionId
                        .computeIfAbsent(a, k -> new ArrayList<>()).add(b);
                    adjacentIntersectionIdsByIntersectionId
                        .computeIfAbsent(b, k -> new ArrayList<>()).add(a);
                }
            }
        }

     // Convert edge pair list to Edge object array
        edges = new Edge[edgePairs.size()];
        for (int i = 0; i < edgePairs.size(); i++) {
            edges[i] = new Edge(edgePairs.get(i)[0], edgePairs.get(i)[1]);
        }
    }

    /**
     * Initializes the robber on the desert tile (tile 16).
     * Must be called after initializeFixedMapLayout().
     */
    public void initializeRobber() {
        // Desert tile is tile index 16
        robberTileId = 16;
        tiles[16].setHasRobber(true);
    }

    /**
     * Returns the tile at the given tile ID, or null if out of range.
     *
     * @param tileId the tile ID to look up
     * @return the Tile, or null
     */
    public Tile getTile(int tileId) {
        if (tileId < 0 || tileId >= tiles.length) return null;
        return tiles[tileId];
    }

    /**
     * Returns the intersection at the given ID, or null if out of range.
     *
     * @param intersectionId the intersection ID
     * @return the Intersection, or null
     */
    public Intersection getIntersection(int intersectionId) {
        if (intersectionId < 0 || intersectionId >= intersections.length) return null;
        return intersections[intersectionId];
    }

    /**
     * Returns an array of all valid intersection IDs (0–53).
     *
     * @return array of all intersection IDs
     */
    public int[] getAllIntersectionIds() {
        int[] ids = new int[intersections.length];
        for (int i = 0; i < intersections.length; i++) ids[i] = i;
        return ids;
    }

    /**
     * Returns all edges on the board.
     *
     * @return array of all Edge objects
     */
    public Edge[] getAllEdges() {
        return edges;
    }

    /**
     * Returns whether the given intersection is occupied by any building.
     *
     * @param intersectionId the intersection ID to check
     * @return true if occupied
     */
    public boolean isIntersectionOccupied(int intersectionId) {
        Intersection inter = getIntersection(intersectionId);
        return inter != null && inter.hasBuilding();
    }

    /**
     * Returns whether the edge between two intersections is occupied.
     *
     * @param intersectionA first endpoint
     * @param intersectionB second endpoint
     * @return true if a road is on this edge
     */
    public boolean isEdgeOccupied(int intersectionA, int intersectionB) {
        for (Edge e : edges) {
            if (e.touchesIntersection(intersectionA) && e.touchesIntersection(intersectionB)) {
                return e.isOccupied();
            }
        }
        return false;
    }

    /**
     * Places a settlement at the given intersection for the given player.
     * Does nothing if the intersection ID is out of range.
     *
     * @param playerId the player placing the settlement
     * @param intersectionId the intersection to place at
     */
    public void placeSettlement(int playerId, int intersectionId) {
        Intersection inter = getIntersection(intersectionId);
        if (inter != null) inter.placeSettlement(playerId);
    }

    /**
     * Upgrades a settlement to a city at the given intersection.
     *
     * @param playerId the player upgrading
     * @param intersectionId the intersection to upgrade
     */
    public void upgradeSettlementToCity(int playerId, int intersectionId) {
        Intersection inter = getIntersection(intersectionId);
        if (inter != null) inter.upgradeToCity(playerId);
    }

    /**
     * Places a road on the edge between two intersections.
     * Does nothing if no such edge exists.
     *
     * @param playerId the player placing the road
     * @param intersectionA  first endpoint
     * @param intersectionB  second endpoint
     */
    public void placeRoad(int playerId, int intersectionA, int intersectionB) {
        for (Edge e : edges) {
            if (e.touchesIntersection(intersectionA) && e.touchesIntersection(intersectionB)) {
                e.placeRoad(playerId);
                return;
            }
        }
    }

    /**
     * Returns all intersection IDs adjacent to the given intersection.
     *
     * @param intersectionId the intersection to look up
     * @return array of adjacent intersection IDs
     */
    public int[] getAdjacentIntersectionIds(int intersectionId) {
        List<Integer> adj = adjacentIntersectionIdsByIntersectionId.get(intersectionId);
        if (adj == null) return new int[0];
        return adj.stream().mapToInt(Integer::intValue).toArray();
    }

    /**
     * Returns all tile IDs adjacent to the given intersection.
     *
     * @param intersectionId the intersection to look up
     * @return array of adjacent tile IDs
     */
    public int[] getAdjacentTileIds(int intersectionId) {
        List<Integer> adj = adjacentTileIdsByIntersectionId.get(intersectionId);
        if (adj == null) return new int[0];
        return adj.stream().mapToInt(Integer::intValue).toArray();
    }

    /**
     * Returns all tiles that produce resources on the given roll.
     * Tiles with the robber on them do not produce even if their number matches.
     *
     * @param roll the dice roll value
     * @return list of producing tiles
     */
    public List<Tile> getTilesProducingOnRoll(int roll) {
        List<Tile> result = new ArrayList<>();
        for (Tile t : tiles) {
            if (t.producesOnRoll(roll)) result.add(t);
        }
        return result;
    }

    /**
     * Returns all intersection IDs adjacent to the given tile.
     *
     * @param tileId the tile ID
     * @return list of adjacent intersection IDs
     */
    public List<Integer> getIntersectionsAdjacentToTile(int tileId) {
        List<Integer> result = new ArrayList<>();
        for (Map.Entry<Integer, List<Integer>> entry : adjacentTileIdsByIntersectionId.entrySet()) {
            if (entry.getValue().contains(tileId)) {
                result.add(entry.getKey());
            }
        }
        return result;
    }

    /**
     * Returns the tile ID the robber is currently on.
     *
     * @return robber tile ID
     */
    public int getRobberTileId() {
        return robberTileId;
    }

    /**
     * Moves the robber to the given tile.
     * Removes the robber from its current tile and places it on the new one.
     *
     * @param newTileId the tile ID to move the robber to
     */
    public void moveRobber(int newTileId) {
    	// Remove robber from current tile
        if (robberTileId >= 0 && robberTileId < tiles.length) {
            tiles[robberTileId].setHasRobber(false);
        }
     // Place robber on new tile
        robberTileId = newTileId;
        if (newTileId >= 0 && newTileId < tiles.length) {
            tiles[newTileId].setHasRobber(true);
        }
    }

    /**
     * Returns all valid tile IDs the robber can move to.
     * Valid = any tile that is not the current robber tile.
     *
     * @return list of valid robber destination tile IDs
     */
    public List<Integer> getValidRobberTiles() {
        List<Integer> valid = new ArrayList<>();
        for (int i = 0; i < tiles.length; i++) {
            if (i != robberTileId) valid.add(i);
        }
        return valid;
    }

    /**
     * Returns player IDs of all players with a building adjacent to the given tile.
     *
     * @param tileId the tile ID
     * @return list of player IDs adjacent to that tile
     */
    public List<Integer> getPlayersAdjacentToTile(int tileId) {
        List<Integer> playerIds = new ArrayList<>();
        for (int intersectionId : getIntersectionsAdjacentToTile(tileId)) {
            Intersection inter = getIntersection(intersectionId);
            if (inter != null && inter.hasBuilding()) {
                Integer ownerId = inter.getBuildingOwnerId();
             // Only add each player once even if they have multiple buildings adjacent
                if (ownerId != null && !playerIds.contains(ownerId)) {
                    playerIds.add(ownerId);
                }
            }
        }
        return playerIds;
    }

    /**
     * Returns the normalized edge key string for display or debug purposes.
     *
     * @param intersectionA first endpoint
     * @param intersectionB second endpoint
     * @return normalized key string e.g. "3-7"
     */
    public String edgeKey(int intersectionA, int intersectionB) {
        return Edge.edgeKey(intersectionA, intersectionB);
    }
}