// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;
import java.util.Random;
/************************************************************/
/** Generates random dice
 * @author komalkhan
 * 
 */ 
public class Dice {
	/**
	 * 
	 */
	private Random rng;

	/**
	 * 
	 * @param rng 
	 */
	public Dice(Random rng) {
		this.rng = rng;
	}

	/**
	 * 
	 * @return 
	 */
	public int rollTwoSixSidedDice() {
		int dice1 = rng.nextInt(6)+1;
		int dice2 = rng.nextInt(6)+1;
		
		return dice1 + dice2;
	}
}