// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/**
 * Represents an edge (road slot) between two intersections on the board.
 *
 * @author Rameen Tariq
 */
public class Edge implements OwnedBoardElement {

    private final int intersectionA;
    private final int intersectionB;
    private int roadOwnerId;

    /**
     * Constructs an unoccupied Edge between two intersections.
     *
     * @param intersectionA first endpoint intersection ID
     * @param intersectionB second endpoint intersection ID
     */
    public Edge(int intersectionA, int intersectionB) {
        this.intersectionA = intersectionA;
        this.intersectionB = intersectionB;
        this.roadOwnerId = -1;
    }

    /**
     * Returns the first endpoint intersection ID.
     *
     * @return intersection A's ID
     */
    public int getIntersectionA() {
        return intersectionA;
    }

    /**
     * Returns the second endpoint intersection ID.
     *
     * @return intersection B's ID
     */
    public int getIntersectionB() {
        return intersectionB;
    }

    /**
     * Returns the ID of the player who owns the road on this edge.
     * Returns -1 if no road has been placed.
     *
     * @return road owner's player ID, or -1
     */
    public int getRoadOwnerId() {
        return roadOwnerId;
    }

    /**
     * Places a road on this edge for the given player.
     * Does nothing if already occupied
     *
     * @param playerId the player placing the road
     */
    public void placeRoad(int playerId) {
        if (!isOccupied()) {
            this.roadOwnerId = playerId;
        }
    }

    /**
     * Returns whether this edge is currently occupied by a road.
     * Implements OwnedBoardElement.isOccupied().
     *
     * @return true if a road has been placed here
     */
    @Override
    public boolean isOccupied() {
        return roadOwnerId != -1;
    }

    /**
     * Returns the owner ID of the road on this edge.
     * Implements OwnedBoardElement.getOwnerId().
     *
     * @return road owner's player ID, or -1 if unowned
     */
    @Override
    public int getOwnerId() {
        return roadOwnerId;
    }

    /**
     * Returns whether this edge connects to the given intersection.
     *
     * @param intersectionId the intersection ID to check
     * @return true if this edge touches that intersection
     */
    public boolean touchesIntersection(int intersectionId) {
        return intersectionA == intersectionId || intersectionB == intersectionId;
    }

    /**
     * Generates a normalized string key for this edge.
     * Always puts the smaller ID first so (2,5) and (5,2) produce
     * the same key "2-5".
     *
     * @param a first endpoint
     * @param b second endpoint
     * @return normalized key string e.g. "2-5"
     */
    public static String edgeKey(int a, int b) {
        int min = Math.min(a, b);
        int max = Math.max(a, b);
        return min + "-" + max;
    }
}
