// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/**
 * Represents a single action taken by a player during their turn.
 *
 * An action involves an intersection, an edge, or both,
 * depending on the action type.
 *
 * @author Maria Shashati
 * 
 */
public class Action {

    private ActionType type;
    private int intersectionId;
    private int edgeIntersectionA;
    private int edgeIntersectionB;

    /**
     * Private constructor
     *
     * @param type the type of action
     * @param intersectionId the intersection involved (-1 if unused)
     * @param edgeIntersectionA  the first edge endpoint (-1 if unused)
     * @param edgeIntersectionB  the second edge endpoint (-1 if unused)
     */
    private Action(ActionType type, int intersectionId,
                   int edgeIntersectionA, int edgeIntersectionB) {
        this.type = type;
        this.intersectionId = intersectionId;
        this.edgeIntersectionA = edgeIntersectionA;
        this.edgeIntersectionB = edgeIntersectionB;
    }

   
    public static Action buildRoad(int intersectionA, int intersectionB) {
        return new Action(ActionType.BUILD_ROAD, -1, intersectionA, intersectionB);
    }

  
    public static Action buildSettlement(int intersectionId) {
        return new Action(ActionType.BUILD_SETTLEMENT, intersectionId, -1, -1);
    }

    
    public static Action buildCity(int intersectionId) {
        return new Action(ActionType.BUILD_CITY, intersectionId, -1, -1);
    }

    
    public static Action pass() {
        return new Action(ActionType.PASS, -1, -1, -1);
    }


    public ActionType getType(){ return type; }
    public int getIntersectionId(){ return intersectionId; }
    public int getEdgeIntersectionA(){ return edgeIntersectionA; }
    public int getEdgeIntersectionB(){ return edgeIntersectionB; }

    /**
     * Returns a human-readable description of this action for game logging.
     *
     * @return a string describing the action
     */
    public String describeForLogger() {
        switch (type) {
            case BUILD_ROAD:
                return "Built road between " + edgeIntersectionA + " and " + edgeIntersectionB;
            case BUILD_SETTLEMENT:
                return "Built settlement at intersection " + intersectionId;
            case BUILD_CITY:
                return "Upgraded to city at intersection " + intersectionId;
            case PASS:
                return "Passed";
            default:
                return "Unknown action";
        }
    }
}