// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Files;

/**
 * This class demonstrates the complete functionality of the Catan game simulator.
 * It initializes and runs a simulation that satisfies all assignment requirements
 * @author Komal Khan, Alisha Faridi
 */
@SuppressWarnings("java:S106")
public class Demonstrator {

	/**
	 * Entry Point for Simulation
	 * 
	 * ASSIGNMENT 1 features demonstrated:
	 * 1. Configuration (R1.4)
	 * - Reads turns from config.txt file
	 * - validates the range given (1 - 8192)
	 * 
	 * 2. Game Initialization 
	 * - Creates game with configured max rounds
	 * - sets up board with fixed tile/intersection layout
	 * - intializes 4 random agents with colours associated (RED, BLUE, GREEN, YELLOW)
	 * - performs initial placement as written in the rulebook
	 * 
	 * 3. Simulation Execution (R1.3-R1.8):
	 * - Runs turn by turn gameplay
	 * - applies all game rules and invariants
	 * - terminates the game when the winning conditions are met (R1.5)
	 * 
	 * 
	 * 
	 * 
	 * ASSIGNMENT 2 features demonstrated:
	 * R2.1  Human commands are parsed by a regex based CommandParser
	 * R2.2  TurnState automaton enforces Roll -> Build -> Go order for Player 1
	 * R2.3  JSON game stae written to gamestate_round_XXXX.json after each round
	 * R2.4  After each AI turn, Player 1 must type "go" to step forward
	 * R2.5  Rollig a 7 activates the robber, players with >7 cards discard half, robber moves to random tile 
	 *       and the current player gets to steal from an adjacent player
	 * R2.6  Visualizer state written to visualize/state.json after each turn
	 * 		 Run "python light_visualizer.py base_map.json - - watch" alongside the game
	 * 		 to see the board working live in the visualize/scraped_boards/
	 * 
	 * 
	 * HOW TO PLAY AS PLAYER 1:
	 * Your turn -> roll -> [build settlement X | build city X | build road X Y | list] -> go
	 * 
	 * After each AI turn -> go (step to the next turn)
	 * 
	 * Cost:
	 * 
	 * Road: WOOD x1, BRICK x1
	 * Settlement: WOOD x1, BRICK x1, WHEAT x1, SHEEP x1
	 * City: WHEAT x2, ORE x3
	 * 
	 */
	public static void main(String[] args) {
		
		int maxRounds = 200;
		
		try {
			maxRounds = readConfigFile("config.txt");
			
		}
		catch(IOException e){
			System.out.println("Could not read config file, using default: " + maxRounds + " rounds");
		}
		
		//Validating that turns value is within acceptable range 
		//R1.4 specifies: turns: int [1-8192]
		
		if (maxRounds < 1 || maxRounds > 8192) {
			System.out.println("Invalid turns value: " + maxRounds + ". Must be between 1-8192. Using default: 200");
			maxRounds = 200;;
		}
		
		
		/**
		 * Creating and intializing gaming
		 * Creating a new game instance with configured max rounds
		 * This satisfies R1.4 (user-defined number of rounds)
		 * 
		 */
		
		Game game = new Game(maxRounds);


		/**
		 * R2.6
		 * Point state.json output at the visualize folder
		 * The python visualizer watches for state.json in its own folder.
		 * This path works as long as program is run from the 
		 * project root directory
		 */
		game.setStateOutputDir(java.nio.file.Paths.get("src/visualize"));
		


		// Clear old scraped boards from previous runs
		java.io.File scrapedDir = new java.io.File("scraped_boards");
		if (scrapedDir.exists() && scrapedDir.isDirectory()) {
			java.io.File[] files = scrapedDir.listFiles();
			if (files != null) {
				for (java.io.File f : files) {
					try {
						Files.delete(f.toPath()); // use NIO delete for better error reporting
					} catch (IOException e) {
						System.out.println("Warning: Failed to delete file " 
							+ f.getName() + " (" + e.getMessage() + ")");
					}
				}
			}
		}
		/**
		 * 
		 * This initializes the game where:
		 * - R1.1: Sets up board with tile IDs and intersection IDs
		 * - R1.2: Creates 4 randomly-acting agents
		 * - Performs initial placement where each player places
		 * - # 2 Settlements and 2 Rounds connecting to settlements and 
		 * - players get initial resources once second settlement is placed
		 * 
		 * Assignment 2 add-ons:
		 * - Each round, each player rolls, recieves resources or activates the robber
		 * - AI players choose randomly from all legal actions
		 * - Player 1 is prompted for commands via the regex parser
		 * - the loop exits when maxRounds is exceeded or any player reaches 10 VP
		 */
		
		
		game.initializeNewGame();
		
		/**
		 * 
		 * Run simulation until termination
		 * - R1.5 Runs round until termination. The game runs turn by turn with
		 * each player rolling dice, recieving resources and trying to build
		 * - R1.8 The action selection uses a linear scan of all possible actions and picks one randomly
		 * - All actions are logged with proper formatting and the game terminates when either maxRounds is exceeded 
		 * or any player reaches 10 VP
		 */
		game.runSimulationUntilTermination();
	}
	
	/**
	 * Reads and parses the configuration file to extract the number of turns
	 * @param filename
	 * @return the number of turns specified in the configuration file
	 * @throws IOException
	 */
	private static int readConfigFile(String filename) throws IOException {
		BufferedReader reader = new BufferedReader(new FileReader(filename));
		String line;
		
		while ((line = reader.readLine()) != null){
			line = line.trim();
			
			if (line.startsWith("#") || line.isEmpty()) {
				continue;
			}
			
			if (line.startsWith("turns:")) {
				String[] parts = line.split(":");
				if (parts.length == 2) {
					reader.close();
					return Integer.parseInt(parts[1].trim());
					
				}
			}
		}
		reader.close();
		throw new IOException("No valid 'turns' configuration found ");
		
	}
	
	
}

