// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/**
 * Represents an intersection (node) on the board where settlements
 * and cities can be placed.
 * 
 * @author Rameen Tariq
 */
public class Intersection implements OwnedBoardElement {

    private final int intersectionId;
    private int buildingOwnerId;
    private Building building;

    /**
     * Creates a new empty Intersection.
     *
     * @param intersectionId this intersection's unique ID
     */
    public Intersection(int intersectionId) {
        this.intersectionId = intersectionId;
        this.buildingOwnerId = -1;
        this.building = null;
    }

    /**
     * Returns this intersection's unique ID.
     *
     * @return the intersection ID
     */
    public int getIntersectionId() {
        return intersectionId;
    }

    /**
     * Returns true if this intersection has no building.
     *
     * @return true if empty
     */
    public boolean isEmpty() {
        return building == null;
    }

    /**
     * Returns true if this intersection has a building.
     *
     * @return true if a building is present
     */
    public boolean hasBuilding() {
        return building != null;
    }

    /**
     * Returns the building type at this intersection.
     *
     * @return the Building enum value, or null if empty
     */
    public Building getBuilding() {
        return building;
    }

    /**
     * Alias for getBuilding() for consistency with Game and Rules.
     *
     * @return the Building enum value, or null if empty
     */
    public Building getBuildingType() {
        return building;
    }

    /**
     * Returns the player ID of the building owner, or null if empty.
     *
     * @return owner's player ID, or null
     */
    public Integer getBuildingOwnerId() {
        if (buildingOwnerId == -1) return null;
        return buildingOwnerId;
    }

    /**
     * Returns the player ID of the building owner, or -1 if empty.
     * Consistent with OwnedBoardElement contract.
     *
     * @return owner's player ID, or -1
     */
    public int getOwnerPlayerId() {
        return buildingOwnerId;
    }

    /**
     * Places a settlement here for the given player.
     * Does nothing if already occupied, so first placement wins.
     *
     * @param playerId the placing player's ID
     */
    public void placeSettlement(int playerId) {
        if (building == null) {
            building = Building.SETTLEMENT;
            buildingOwnerId = playerId;
        }
    }

    /**
     * Upgrades an existing settlement to a city.
     * Does nothing if the intersection is not owned by this player
     * or does not have a settlement.
     *
     * @param playerId the upgrading player's ID
     */
    public void upgradeToCity(int playerId) {
        if (building == Building.SETTLEMENT && buildingOwnerId == playerId) {
            building = Building.CITY;
        }
    }

    /**
     * Returns whether this intersection has a building on it.
     * Implements OwnedBoardElement.isOccupied().
     *
     * @return true if a building is present
     */
    @Override
    public boolean isOccupied() {
        return building != null;
    }

    /**
     * Returns the owner ID of the building at this intersection.
     * Implements OwnedBoardElement.getOwnerId().
     *
     * @return building owner's player ID, or -1 if unowned
     */
    @Override
    public int getOwnerId() {
        return buildingOwnerId;
    }
    
    /**
     * Removes the building at this intersection, resetting it to empty.
     * Used by undo operations in the Command Pattern (R3.1).
     */
    public void clearBuilding() {
        building = null;
        buildingOwnerId = -1;
    }

    /**
     * Sets the building type at this intersection directly.
     * Used by undo operations in the Command Pattern (R3.1).
     *
     * @param building the building type to set
     */
    public void setBuilding(Building building) {
        this.building = building;
    }
}