// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import java.security.SecureRandom;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;


/**
 * Represents a player in the Catan simulator.
 *
 * A Player stores identity, victory points, resource cards,
 * owned buildings, and owned roads.
 *
 * @author Maria Shashati, Komal Khan
 */
public class Player {

	 /** Unique identifier for this player. */
    private int playerId;
    
    /** Colour assigned to this player. */
    private Colour colour;
    
    /** Current victory point total. */
    private int victoryPoints;

    /**
     * Resource cards held by the player.
     * Key = resource type, Value = quantity owned.
     */
    
    /**
     * Resource cards held by the player.
     * Key = resource type, Value = quantity owned.
     */
    private Map<Resources, Integer> resourceCards;


    /**
     * Buildings owned by the player.
     * Key = intersection ID, Value = building type (SETTLEMENT or CITY).
     */
    private Map<Integer, Building> ownedBuildings;

    /**
     * Normalized edge keys for roads owned by the player.
     * Format: "min-max" where min and max are intersection IDs.
     */
    private Set<String> ownedRoadEdgeKeys;

    private final SecureRandom rng;

    /**
     * Constructs a new Player with the given ID and colour
     *
     * @param playerId the unique identifier for the player
     * @param colour the colour assigned to the player
     */
    public Player(int playerId, Colour colour) {
        this.playerId = playerId;
        this.colour = colour;
        this.victoryPoints = 0;
        this.rng = new SecureRandom();

        // Initialize all collections as empty
        this.resourceCards = new HashMap<>();
        this.ownedBuildings = new HashMap<>();
        this.ownedRoadEdgeKeys = new HashSet<>();
    }

    /**
     * Returns the player's unique ID
     *
     * @return the player ID
     */
    public int getPlayerId() {
        return playerId;
    }

    /**
     * Returns the player's colour
     *
     * @return the player's colour
     */
    public Colour getColour() {
        return colour;
    }

    /**
     * Returns the player's current victory points
     *
     * @return the current victory point total
     */
    public int getVictoryPoints() {
        return victoryPoints;
    }

    /**
     * Adds victory points to the player's total
     *
     * @param points the number of points to add
     */
    public void addVictoryPoints(int points) {
        victoryPoints += points;
    }

    /**
     * Returns the total number of resource cards in the player's hand.
     * Sums all quantities across all resource types.
     *
     * @return the total number of resource cards in hand
     */
    public int getTotalCardsInHand() {
        int total = 0;
     // Sum up counts for every resource type
        for (int count : resourceCards.values()) {
            total += count;
        }
        return total;
    }

    /**
     * Adds a given amount of a resource to the player's hand.
     * If the player already has some of this resource, the amount is added on top.
     *
     * @param type   the type of resource to add
     * @param amount the number of cards to add
     */
    public void addResource(Resources type, int amount) {
    	// getOrDefault handles the case where player has none of this resource yet
        resourceCards.put(type, resourceCards.getOrDefault(type, 0) + amount);
    }

    /**
     * Checks whether the player has enough resources to pay a given cost
     *
     * @param cost a map describing the required resources
     * @return true if the player can afford the cost otherwise false 
     */
    public boolean hasEnoughResources(Map<Resources, Integer> cost) {
        for (Resources type : cost.keySet()) {
            int owned = resourceCards.getOrDefault(type, 0);
         // Fail fast if any single resource is insufficient
            if (owned < cost.get(type)) {
                return false;
            }
        }
        return true;
    }

    /**
     * Deducts resources from the player's hand based on the given cost.
     * Throws an exception if the player cannot afford the cost — callers
     * should always check hasEnoughResources() first.
     *
     * @param cost a map describing the resources to deduct
     * @throws IllegalArgumentException if the player cannot afford the cost
     */
    public void payCost(Map<Resources, Integer> cost) {
    	
    	// should never be reached if caller checks first
    	if (!hasEnoughResources(cost)) {
              throw new IllegalArgumentException(
                  "Player " + playerId + " does not have enough resources to pay the cost.");
          }

    	// Deduct each resource in the cost map
        for (Resources type : cost.keySet()) {
            int remaining = resourceCards.getOrDefault(type, 0) - cost.get(type);
            resourceCards.put(type, remaining);
        }
    }

    /**
     * Checks whether the player owns a settlement at that intersection 
     *
     * @param intersectionId the intersection ID to check
     * @return true if the player owns a settlement at that intersection otherwise false 
     */
    public boolean ownsSettlementAt(int intersectionId) {
        return ownedBuildings.containsKey(intersectionId) 
            && ownedBuildings.get(intersectionId) == Building.SETTLEMENT;
    }

    /**
     * Checks whether the player owns at least one road connected to a given intersection.
     * Uses the normalized edge key format to match roads at either endpoint.
     *
     *
     * @param intersectionId the intersection ID to check
     * @param board the board instance 
     * @return true if any owned road touches this intersection otherwise false 
     */
    public boolean ownsRoadConnectedTo(int intersectionId, Board board) {
        if (board == null) {
            return false;
        }

        // Check both endpoints of each owned road edge key
        for (String key : ownedRoadEdgeKeys) {
            if (key.startsWith(intersectionId + "-") || key.endsWith("-" + intersectionId)) {
                return true;
            }
        }
        return false;
    }

    /**
     * Records that the player placed a settlement at the given intersection
     * Note: Victory points are added in Game.executeAction, not here
     *
     * @param intersectionId the intersection where the settlement was placed
     */
    public void recordPlacedSettlement(int intersectionId) {
        ownedBuildings.put(intersectionId, Building.SETTLEMENT);
    }

    /**
     * records that player upgraded from settlement to city at intersection
     * Note: Victory points are added in Game.executeAction, not here
     *
     * @param intersectionId the intersection where the city upgrade occurred
     */
    public void recordUpgradedCity(int intersectionId) {
        ownedBuildings.put(intersectionId, Building.CITY);
    }

    /**
     * Records that the player placed a road between two intersections.
     * Stores a normalized edge key so road lookups are order-independent.
     *
     * @param intersectionA the first endpoint intersection ID
     * @param intersectionB the second endpoint intersection ID
     */
    public void recordPlacedRoad(int intersectionA, int intersectionB) {
        ownedRoadEdgeKeys.add(edgeKey(intersectionA, intersectionB));
    }

    /**
     * Generates a normalized edge key for a road between two intersections.
     * Always stores the smaller ID first so the key is order-independent.
     * e.g. edge(5,3) and edge(3,5) both produce "3-5".
     *
     * @param intersectionA the first endpoint intersection ID
     * @param intersectionB the second endpoint intersection ID
     * @return a String key representing the edge
     */
    public String edgeKey(int intersectionA, int intersectionB) {
        int min = Math.min(intersectionA, intersectionB);
        int max = Math.max(intersectionA, intersectionB);
        return min + "-" + max;
    }
    
    
    /**
     * Removes a specific amount of a resource from the player's hand.
     * Used for card stealing and discarding. Will not go below zero.
     *
     * @param type   the resource type to remove
     * @param amount the number of cards to remove
     */
    public void removeResources(Resources type, int amount) {
    	int current = resourceCards.getOrDefault(type, 0);
    	int newAmount = Math.max(0,  current - amount);
    	resourceCards.put(type,  newAmount);
    	
    	
    }
    
    /**
     * Discards half of the player's cards when they have more than 7
     * and a 7 is rolled. Cards are chosen randomly to simulate the
     * computer player selecting which to discard.
     *
     * @return the number of cards discarded, or 0 if hand size is 7 or fewer
     */
    
    public int discardHalfCards() {
    	int totalCards = getTotalCardsInHand();
    	
    	// No discard needed if hand size is 7 or fewer
    	if(totalCards <= 7) {
    		return 0;
    	}
    	
    	// player discards floor(total/2)
    	int haveToDiscard = totalCards / 2; 
    	int discarded = 0;
    	
    	 // Build a flat list of all individual resource cards in hand
    	List<Resources> allCards = new ArrayList<>();
    	for(Map.Entry<Resources, Integer> entry: resourceCards.entrySet()) {
    		Resources type = entry.getKey();
    		int count = entry.getValue();
    		for(int x = 0; x <count; x++) {
    			allCards.add(type);
    		}
    	}
    	
    	// Randomly pick and remove cards one at a time until discard quota is met
    	SecureRandom r = new SecureRandom();
    	for (int x = 0; x < haveToDiscard && !allCards.isEmpty(); x++) {
    		int randomNum = rng.nextInt(allCards.size());
    		Resources typeToRemove = allCards.remove(randomNum);
    		removeResources(typeToRemove, 1);
    		discarded++;
    	}
    	
    	return discarded;
    	
    	
    }
    
    
    /**
     * Returns a random resource card from the player's hand.
     * Used when another player steals from this player via the robber.
     *
     * @return a random Resources type the player owns,
     *         or null if the player has no cards
     */
    public Resources getRandomResource() {
    	// Build a flat list of all individual resource cards in hand
    	List<Resources> allCards = new ArrayList<>();
    	
    	for(Map.Entry<Resources, Integer> entry: resourceCards.entrySet()) {
    		Resources type = entry.getKey();
    		int count = entry.getValue();
    		for (int x = 0; x < count; x++) {
    			allCards.add(type);
    		}
    	}
    	
    	// Return null if player has nothing to steal
    	if(allCards.isEmpty()) {
    		return null;
    	}
    	
    	 // Pick a random card from the flat list
    	SecureRandom r = new SecureRandom();
    	return allCards.get(rng.nextInt(allCards.size()));
    	
    	
    }
    
    /**
     * Returns a defensive copy of the player's resource cards.
     * The copy prevents external classes from modifying the player's
     * hand directly.
     *
     * @return a copy of the resource cards map
     */
    public Map<Resources, Integer>  getResourceCards(){
    	// Return a copy bc we never expose the internal map directly
    	return new HashMap<>(resourceCards);
    }
    
    
    /**
     * Returns all buildings owned by this player
     * Used for game state export
     * 
     * @return map of intersection ID to building type
     */
    public Map<Integer, Building> getOwnedBuildings(){
    	return new HashMap<>(ownedBuildings);
    }
}