// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

import java.util.ArrayList;
import java.util.Collections;
import java.util.EnumMap;
import java.util.Map;
import java.util.List;
import java.util.Random;

/**
 * Encodes all building and placement rules for the Catan simulator.
 *
 * @author Alisha Faridi
 */
public class Rules {

    private final Map<ActionType, Map<Resources, Integer>> actionCosts;

    public Rules() {
        this.actionCosts = new EnumMap<>(ActionType.class);

        actionCosts.put(ActionType.BUILD_ROAD, costOf(
                Resources.WOOD, 1,
                Resources.BRICK, 1
        ));

        actionCosts.put(ActionType.BUILD_SETTLEMENT, costOf(
                Resources.WOOD, 1,
                Resources.BRICK, 1,
                Resources.WHEAT, 1,
                Resources.SHEEP, 1
        ));

        actionCosts.put(ActionType.BUILD_CITY, costOf(
                Resources.WHEAT, 2,
                Resources.ORE, 3
        ));

        actionCosts.put(ActionType.PASS, Collections.emptyMap());
    }

    private Map<Resources, Integer> costOf(Object... pairs) {
        Map<Resources, Integer> map = new EnumMap<>(Resources.class);
        for (int i = 0; i < pairs.length; i += 2) {
            map.put((Resources) pairs[i], (Integer) pairs[i + 1]);
        }
        return map;
    }

    /**
     * Returns whether the player can legally build a road on the given edge.
     *
     * @param player the player attempting to build
     * @param board the current board state
     * @param edge the edge to build on
     * @return true if the road placement is legal
     */
    public boolean canBuildRoad(Player player, Board board, Edge edge) {
        if (edge == null) return false;
        if (edge.isOccupied()) return false;
        return isRoadConnectedToPlayerNetwork(player, board, edge);
    }

    /**
     * Returns whether the player can legally build a settlement at the given intersection.
     *
     * @param player the player attempting to build
     * @param board the current board state
     * @param intersectionId the intersection to build at
     * @return true if the settlement placement is legal
     */
    public boolean canBuildSettlement(Player player, Board board, int intersectionId) {

        // intersection must be unoccupied
        if (board.isIntersectionOccupied(intersectionId)) {
            return false;
        }

        // no adjacent intersection may be occupied
        if (!isDistanceRuleSatisfied(board, intersectionId)) {
            return false;
        }

        // settlement must connect to player's road network.
        if (!player.ownsRoadConnectedTo(intersectionId, board)) {
            return false; 
        }

        return true;
    }

    /**
     * Returns whether a settlement can legally be placed at the given intersection during the initial place phase
     * @param board the current board state
     * @param intersectionId the intersection to check
     * @return true if the location is legal for initial placement
     */
    public boolean canPlaceInitialSettlement(Board board, int intersectionId){
        if (board.isIntersectionOccupied(intersectionId)){
            return false;
        }

        if (!isDistanceRuleSatisfied(board, intersectionId)){
            return false;
        }

        return true;
    }

    /**
     * Returns whether the player can legally upgrade a settlement to a city.
     *
     * @param player the player attempting to upgrade
     * @param board the current board state
     * @param intersectionId the intersection to upgrade at
     * @return true if the city upgrade is legal
     */
    public boolean canBuildCity(Player player, Board board, int intersectionId) {
        Intersection intersection = board.getIntersection(intersectionId);
        if (intersection == null) return false;

        Integer ownerId = intersection.getBuildingOwnerId();
        Building type = intersection.getBuildingType();

        if (ownerId == null || type == null) return false;
        if (ownerId != player.getPlayerId()) return false;

        // Must currently be a settlement
        return type == Building.SETTLEMENT;
    }

    /**
     * Returns all legal actions for the player via a linear scan of the board.
     *
     * @param player the player whose actions to enumerate
     * @param board the current board state
     * @return list of all legal actions; contains at least PASS
     */
    public List<Action> getValidActionsByLinearScan(Player player, Board board) {
        List<Action> actions = new ArrayList<>();

        for (int intersectionId : board.getAllIntersectionIds()) {
            if (canBuildSettlement(player, board, intersectionId)) {
                actions.add(Action.buildSettlement(intersectionId));
            }
            if (canBuildCity(player, board, intersectionId)) {
                actions.add(Action.buildCity(intersectionId));
            }
        }

        for (Edge e : board.getAllEdges()) {
            if (canBuildRoad(player, board, e)) {
                actions.add(Action.buildRoad(e.getIntersectionA(), e.getIntersectionB()));
            }
        }

        if (actions.isEmpty()) {
            actions.add(Action.pass());
        }

        return actions;
    }

    /**
     * Returns the resource cost for the given action type.
     *
     * @param actionType the type of action to look up
     * @return a map of resource types to quantities required
     */
    public Map<Resources, Integer> getCost(ActionType actionType) {
        Map<Resources, Integer> cost = actionCosts.get(actionType);
        return (cost == null) ? Collections.emptyMap() : cost;
    }

    /**
     * Selects a random action from the list of valid actions.
     * Returns PASS if the list is null or empty.
     *
     * @param validActions the list of legal actions
     * @param rng the random number generator
     * @return the chosen action
     */
    public Action chooseRandomAction(List<Action> validActions, Random rng) {
        if (validActions == null || validActions.isEmpty()) {
            return Action.pass();
        }
        return validActions.get(rng.nextInt(validActions.size()));
    }

    /**
     * Returns true if the distance rule is satisfied at the given intersection.
     */
    private boolean isDistanceRuleSatisfied(Board board, int intersectionId) {
        for (int neighbourId : board.getAdjacentIntersectionIds(intersectionId)) {
            if (board.isIntersectionOccupied(neighbourId)) {
                return false;
            }
        }
        return true;
    }

    /**
     * Returns true if a road placement is connected to the player's network.
     * A road is connected if either endpoint is:
     * - adjacent to an existing player road, or
     * - occupied by a player building.
     */
    private boolean isRoadConnectedToPlayerNetwork(Player player, Board board, Edge edge) {
        int a = edge.getIntersectionA();
        int b = edge.getIntersectionB();

        return player.ownsRoadConnectedTo(a, board)
            || player.ownsRoadConnectedTo(b, board)
            || playerOwnsBuildingAt(player, board, a)
            || playerOwnsBuildingAt(player, board, b);
    }

    /**
     * Returns true if the player owns a building at the given intersection.
     */
    private boolean playerOwnsBuildingAt(Player player, Board board, int intersectionId) {
        Intersection intersection = board.getIntersection(intersectionId);
        if (intersection == null) return false;
        Integer ownerId = intersection.getBuildingOwnerId();
        return ownerId != null && ownerId == player.getPlayerId();
    }

    
}