// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/**
 * Represents a resource tile on the board
 * 
 * Each tile has a resource type, a dice number token that activates it,
 * and a robber flag that blocks production when the robber is present.
 *
 * @author Rameen Tariq, Komal Khan
 * 
 *
 */
public class Tile {
    private int tileId;
    private int diceNumberToken;
    private Resources resource;

    
    /**
     * Tracks whether the robber is currently on this tile.
     * When true, this tile does not produce resources even if its
     * dice number is rolled (Assignment 2 addition).
     */
    private boolean hasRobber;
    
    
    
    /**
     *
     * Creates a new Tile
     * Robber defaults to false so no tile starts with the robber.
     * 
     * @param tileId The unique ID of the tile
     * @param resource The resource type of the tile
     * @param diceNumberToken The dice number that activates this tile
     */
    public Tile(int tileId, Resources resource, int diceNumberToken) {
        this.tileId = tileId;
        this.resource = resource;
        this.diceNumberToken = diceNumberToken;
    }

    /**
     * Returns the Id of the tile
     *
     * @return The tile ID
     */
    public int getTileId() {
        return this.tileId;
    }

    /**
     * Returns the resource type of this tile
     *
     * @return The resource type
     */
    public Resources getResource() {
        return this.resource;
    }

    /**
      * Returns the dice number token that activates this tile.
     *
     * @return The dice number token
     */
    public int getDiceNumberToken() {
        return this.diceNumberToken;
    }
    
    
    /**
     * 
     * Sets whether the robber
     * @param hasRobber set to true if robber should be place here, if false then need to remove
     * 
     */
    
    public void setHasRobber(boolean hasRobber) {
    	this.hasRobber = hasRobber;
    }
    
    

    /**
     * Checks if this tile produces resources for a given dice roll.
     *
     * A tile produces resources only if all three conditions are met:
     * - The dice roll matches the tile's number token
     * - The tile is not a DESERT
     * - The robber is not currently on this tile
     *
     * @param roll the dice roll value to check against
     * @return true if this tile produces resources on this roll
     */
    public boolean producesOnRoll(int roll) {
    	// Robber blocks all production regardless of roll
    	if (this.hasRobber) {
    		return false;
    	}
        if (roll == this.diceNumberToken) {
        	// Desert tiles never produce resources
            if (this.resource != Resources.DESERT) {
                return true;
            }
        }
        return false;
    }
}
