// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public enum ActionType {
	/**
	 * 
	 */
	BUILD_ROAD,
	/**
	 * 
	 */
	BUILD_SETTLEMENT,
	/**
	 * 
	 */
	BUILD_CITY,
	/**
	 * 
	 */
	PASS;
}
