// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class Intersection {
	/**
	 * 
	 */
	private int intersectionId;
	/**
	 * 
	 */
	private int buildingOwnerId;
	/**
	 * 
	 */
	private Building building;

	/**
	 * 
	 * @param intersectionId 
	 */
	public void Intersection(int intersectionId) {
	}

	/**
	 * 
	 * @return 
	 */
	public int getIntersectionId() {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean isEmpty() {
	}

	/**
	 * 
	 * @return 
	 */
	public Building getBuilding() {
	}

	/**
	 * 
	 * @param playerId 
	 * @return 
	 */
	public void placeSettlement(int playerId) {
	}

	/**
	 * 
	 * @param playerId 
	 * @return 
	 */
	public void upgradeToCity(int playerId) {
	}
}
