// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class ResourceCostEntry {
	/**
	 * 
	 */
	public int amount;
	/**
	 * 
	 */
	public Resources ResourceType;
}
