// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class Board {
	/**
	 * 
	 */
	public class Class1 {
	};

	/**
	 * 
	 */
	private Tile[] tiles;
	/**
	 * 
	 */
	public Intersection[] intersections;
	/**
	 * 
	 */
	public Edge[] edges;
	/**
	 * 
	 */
	public IntToIntListEntry[] adjacentIntersectionIdsByIntersectionId;
	/**
	 * 
	 */
	public IntToIntListEntry[] adjacentTileIdsByIntersectionId;

	/**
	 * 
	 */
	public void Board() {
	}

	/**
	 * 
	 * @return 
	 */
	public void initializeFixedMapLayout() {
	}

	/**
	 * 
	 * @param tileId 
	 * @return 
	 */
	public Tile getTile(int tileId) {
	}

	/**
	 * 
	 * @param intersectionId 
	 * @return 
	 */
	public Intersection getIntersection(int intersectionId) {
	}

	/**
	 * 
	 * @return 
	 */
	public int[] getAllIntersectionIds() {
	}

	/**
	 * 
	 * @param intersectionId 
	 * @return 
	 */
	public boolean isIntersectionOccupied(int intersectionId) {
	}

	/**
	 * 
	 * @param intersectionA 
	 * @param intersectionB 
	 * @return 
	 */
	public boolean isEdgeOccupied(int intersectionA, int intersectionB) {
	}

	/**
	 * 
	 * @param playerId 
	 * @param intersectionId 
	 * @return 
	 */
	public void upgradeSettlementToCity(int playerId, int intersectionId) {
	}

	/**
	 * 
	 * @return 
	 */
	public Edge[] getAllEdges() {
	}

	/**
	 * 
	 * @return 
	 * @param intersectinId 
	 */
	public int[] getAdjacentIntersectionIds(int intersectinId) {
	}

	/**
	 * 
	 * @param playerId 
	 * @param intersectionId 
	 * @return 
	 */
	public void placeSettlement(int playerId, int intersectionId) {
	}

	/**
	 * 
	 * @return 
	 * @param intersectionIds 
	 */
	public int[] getAdjacentTileIds(int intersectionIds) {
	}

	/**
	 * 
	 * @param playerId 
	 * @param intersectionA 
	 * @param intersectionB 
	 * @return 
	 */
	public void placeRoad(int playerId, int intersectionA, int intersectionB) {
	}

	/**
	 * 
	 * @param intersectionA 
	 * @param intersectionB 
	 * @return 
	 */
	private String edgeKey(int intersectionA, int intersectionB) {
	}
}
