// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/**
 * The Building enum represents the different types of structures that players can build during their turn
 * Each building type contributes a different number of victory points.
 *
 * @author Maria Shashati
 * @version 1.0
 *
 */
public enum Building {
	SETTLEMENT,
	
	CITY;

/**
 * Returns the number of victory points awarded for this building type.
 *
 * @return The victory points associated with the building type.
 */
public int getVictoryPoints() {
    switch (this) {
        case SETTLEMENT:
            return 1;
        case CITY:
            return 2;
        default:
            return 0;
    }
}
}
