// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/**
 * The PlayerColor enum represents the colour assigned to each player participating during their turn.
 * Player colours are used to distinguish players during the game and output logging.
 *
 * @author Maria Shashati
 * @version 1.0
 *
 */
public enum Colour {
	
	RED,
	
	BLUE,
	
	GREEN,
	
	YELLOW;

/**
 * Returns a formatted display name of the player colour.
 *
 * @return A string representing the player colour in title case
 */
public String getDisplayName() {
    return name().charAt(0) + name().substring(1).toLowerCase();
	}

}
