// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * Demonstrator class to run the Catan game simulation
 */
public class Demonstrator {

	/**
	 * Main method to start the game
	 */
	public static void main(String[] args) {
		Game game = new Game(200);

		game.initializeNewGame();
		game.runSimulationUntilTermination();
	}
}

