// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class IntToIntListEntry {
	/**
	 * 
	 */
	public int key;
	/**
	 * 
	 */
	public int value;
}
