// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/**
 * The Resources enum represents the different resources a player can obtain.
 *
 * @author Alisha Faridi
 * @version 1.0
 *
 */

public enum Resources {
	BRICK,
	WHEAT,
	WOOD,
	SHEEP,
	ORE,
	DESERT;
}
