// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class ActionCostEntry {
	/**
	 * 
	 */
	public ActionType ActionType;
	/**
	 * 
	 */
	public ResourceCostEntry[] Cost;
}
