// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class Action {
	/**
	 * 
	 */
	private ActionType type;
	/**
	 * 
	 */
	public int intersectionId;
	/**
	 * 
	 */
	public int edgeIntersectionIdA;
	/**
	 * 
	 */
	public int edgeIntersectionB;

	/**
	 * 
	 * @param type 
	 * @param intersectionId 
	 * @param edgeIntersectionA 
	 * @param edgeIntersectionB 
	 */
	public void Action(ActionType type, int intersectionId, int edgeIntersectionA, int edgeIntersectionB) {
	}

	/**
	 * 
	 * @return 
	 */
	public ActionType getType() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getIntersectionId() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getEdgeIntersectionA() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getEdgeIntersectionB() {
	}

	/**
	 * 
	 * @return 
	 */
	public String describeForLogin() {
	}
}
