// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class Demonstrator {
	/**
	 * 
	 */
	public class Class1 {
	};

	/**
	 * 
	 */
	public void static void main (String[] args)() {
	}
}
