// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class Dice {
	/**
	 * 
	 */
	private Random rng;

	/**
	 * 
	 * @param rng 
	 */
	public void Dice(Random rng) {
	}

	/**
	 * 
	 * @return 
	 */
	public int rollTwoSixSidedDice() {
	}
}
