// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class Edge {
	/**
	 * 
	 */
	private int intersectionA;
	/**
	 * 
	 */
	private int intersectionB;
	/**
	 * 
	 */
	private int roadOwnerId;

	/**
	 * 
	 * @param intersectionA 
	 * @param intersectionB 
	 */
	public void Edge(int intersectionA, int intersectionB) {
	}

	/**
	 * 
	 * @return 
	 */
	public int getIntersectionA() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getIntersectionB() {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean isOccupied() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getRoadOwnerId() {
	}

	/**
	 * 
	 * @param playerId 
	 * @return 
	 */
	public void placeRoad(int playerId) {
	}

	/**
	 * 
	 * @param intersectionId 
	 * @return 
	 */
	public boolean touchesIntersection(int intersectionId) {
	}
}
