// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class Game {
	/**
	 * 
	 */
	private Board board;
	/**
	 * 
	 */
	private Player[] players;
	/**
	 * 
	 */
	private Rules rules;
	/**
	 * 
	 */
	private Dice dice;
	/**
	 * 
	 */
	private Random rng;
	/**
	 * 
	 */
	private int roundNumber;
	/**
	 * 
	 */
	private int maxRounds;
	/**
	 * 
	 */
	private int victoryPointsToWin;
	/**
	 * 
	 */
	public Player player;

	/**
	 * 
	 * @param maxRounds 
	 */
	public void Game(int maxRounds) {
	}

	/**
	 * 
	 * @return 
	 */
	public void initializeNewGame() {
	}

	/**
	 * 
	 * @return 
	 */
	public void runSimulationUntilTermination() {
	}

	/**
	 * 
	 * @return 
	 */
	public void playOneRound() {
	}

	/**
	 * 
	 * @param player 
	 * @return 
	 */
	public void playOneTurn(Player player) {
	}

	/**
	 * 
	 * @return 
	 */
	public int rollDice() {
	}

	/**
	 * 
	 * @param roll 
	 * @return 
	 */
	public void distributeResourcesForRoll(int roll) {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean isTerminationReached() {
	}

	/**
	 * 
	 * @return 
	 */
	public Player getWinnerOrNull() {
	}

	/**
	 * 
	 * @return 
	 */
	public void printRoundScoreboard() {
	}
}
