// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class Login {
	/**
	 * 
	 */
	private String actionFormatTemplate;

	/**
	 * 
	 */
	public void Login() {
	}

	/**
	 * 
	 * @param roundNumber 
	 * @param playerId 
	 * @param actionText 
	 * @return 
	 */
	public void printTurnAction(int roundNumber, int playerId, String actionText) {
	}

	/**
	 * 
	 * @param maxRounds 
	 * @return 
	 */
	public void printGameStart(int maxRounds) {
	}

	/**
	 * 
	 * @param winnerOrNull 
	 * @param roundNumber 
	 * @return 
	 */
	public void printGameOver(Player winnerOrNull, int roundNumber) {
	}
}
