// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class OwnedBuildings {
	/**
	 * 
	 */
	public int intersectionId;
	/**
	 * 
	 */
	public Building building;
}
