// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class Player {
	/**
	 * 
	 */
	private int playerId;
	/**
	 * 
	 */
	private Colour colour;
	/**
	 * 
	 */
	private int victoryPoints;
	/**
	 * 
	 */
	private ResourceCostEntry[] resourceCards;
	/**
	 * 
	 */
	public OwnedBuildings[] ownedBuildings;
	/**
	 * 
	 */
	public String[] ownedRoadEdgeKeys;

	/**
	 * 
	 * @param playerId 
	 * @param colour 
	 */
	public void Player(int playerId, Colour colour) {
	}

	/**
	 * 
	 * @return 
	 */
	public int getPlayerId() {
	}

	/**
	 * 
	 * @return 
	 */
	public Colour getColour() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getVictoryPoints() {
	}

	/**
	 * 
	 * @param points 
	 * @return 
	 */
	public void addVictoryPoints(int points) {
	}

	/**
	 * 
	 * @return 
	 */
	public int getTotalCardsInHand() {
	}

	/**
	 * 
	 * @param type 
	 * @param amount 
	 * @return 
	 */
	public void addResource(Resources type, int amount) {
	}

	/**
	 * 
	 * @return 
	 * @param  
	 */
	public boolean hasEnoughResources(ResourceCostEntry[] ) {
	}

	/**
	 * 
	 * @return 
	 * @param  
	 */
	public void payCost(ResourceCostEntry[] ) {
	}

	/**
	 * 
	 * @param intersectionId 
	 * @return 
	 */
	public boolean ownsSettlementAt(int intersectionId) {
	}

	/**
	 * 
	 * @param intersectionId 
	 * @param board 
	 * @return 
	 */
	public boolean ownsRoadConnectedTo(int intersectionId, Board board) {
	}

	/**
	 * 
	 * @param intersectionId 
	 * @return 
	 */
	public void recordPlacedSettlement(int intersectionId) {
	}

	/**
	 * 
	 * @param intersectionId 
	 * @return 
	 */
	public void recordUpgradedCity(int intersectionId) {
	}

	/**
	 * 
	 * @param intersectionA 
	 * @param intersectionB 
	 * @return 
	 */
	public void recordPlacedRoad(int intersectionA, int intersectionB) {
	}

	/**
	 * 
	 * @param intersectionA 
	 * @param intersectionB 
	 * @return 
	 */
	private String edgeKey(int intersectionA, int intersectionB) {
	}
}
