// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class Rules {
	/**
	 * 
	 */
	public class Class1 {
	};

	/**
	 * 
	 */
	public class Class2 {
	};

	/**
	 * 
	 */
	public ActionCostEntry[] actionCosts;

	/**
	 * 
	 */
	public void Rules() {
	}

	/**
	 * 
	 * @param player 
	 * @param board 
	 * @param edge 
	 * @return 
	 */
	public boolean canBuildRoad(Player player, Board board, Edge edge) {
	}

	/**
	 * 
	 * @param player 
	 * @param board 
	 * @param intersectionId 
	 * @return 
	 */
	public boolean canBuildSettlement(Player player, Board board, int intersectionId) {
	}

	/**
	 * 
	 * @param player 
	 * @param board 
	 * @param intersectionId 
	 * @param  
	 */
	public void canBuildCity(Player player, Board board, int intersectionId, boolean ) {
	}

	/**
	 * 
	 * @param player 
	 * @param board 
	 * @return 
	 */
	public Action getValidActionsByLinearScan(Player player, Board board) {
	}

	/**
	 * 
	 * @param actionType 
	 * @param  
	 */
	public void getCost(ActionType actionType, ResourceCostEntry[] ) {
	}

	/**
	 * 
	 * @return 
	 * @param  
	 */
	public Action chooseRandomAction(Action[] ) {
	}

	/**
	 * 
	 * @param board 
	 * @param intersectionId 
	 * @return 
	 */
	private boolean isDistanceRuleSatisfied(Board board, int intersectionId) {
	}

	/**
	 * 
	 * @param player 
	 * @param board 
	 * @param edge 
	 */
	private void isRoadConnectedToPLayerNetwork(Player player, Board board, Edge edge) {
	}
}
