// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class Tile {
	/**
	 * 
	 */
	private int tileId;
	/**
	 * 
	 */
	private int diceNumberToken;
	/**
	 * 
	 */
	public Resources resource;

	/**
	 * 
	 * @param tileId 
	 * @param resource 
	 * @param diceNumberToken 
	 */
	public void Tile(int tileId, Resources resource, int diceNumberToken) {
	}

	/**
	 * 
	 * @return 
	 */
	public int getTileId() {
	}

	/**
	 * 
	 * @return 
	 */
	public Resources getResource() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getDiceNumberToken() {
	}

	/**
	 * 
	 * @param roll 
	 * @return 
	 */
	public boolean producesOnRoll(int roll) {
	}
}
